In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import pandas as pd
from selenium.webdriver.common.by import By
from time import sleep

In [2]:
url = 'https://www.flashscore.com.ng/team/crvena-zvezda/6uAuZ6Pt/results/'

In [3]:
driver = webdriver.Chrome(executable_path = r"C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe")
driver.get(url)
ID = 'id'

C:\Users\user\AppData\Local\Temp\ipykernel_11280\600623497.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path = r"C:\Users\user\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [234]:
games = driver.find_elements(By.CLASS_NAME, 'event__match--twoLine')
gamesbase = []

for game in games:
    home_team = game.find_element(By.CLASS_NAME, 'event__participant--home').text
    away_team = game.find_element(By.CLASS_NAME, 'event__participant--away').text    
    
    first_quarter_home = game.find_element("xpath", './/*[@class="event__part event__part--home event__part--1"]').text
    second_quarter_home = game.find_element("xpath", './/*[@class="event__part event__part--home event__part--2"]').text
    third_quarter_home = game.find_element("xpath", './/*[@class="event__part event__part--home event__part--3"]').text
    fourth_quarter_home = game.find_element("xpath", './/*[@class="event__part event__part--home event__part--4"]').text
    first_quarter_away = game.find_element("xpath", './/*[@class="event__part event__part--away event__part--1"]').text
    second_quarter_away = game.find_element("xpath", './/*[@class="event__part event__part--away event__part--2"]').text
    third_quarter_away = game.find_element("xpath", './/*[@class="event__part event__part--away event__part--3"]').text
    fourth_quarter_away = game.find_element("xpath", './/*[@class="event__part event__part--away event__part--4"]').text

    event_time = game.find_element("xpath", './/*[@class="event__time"]').text
    
    event_item = {
        'home_team': home_team,
        'away_team': away_team,
        'first_quarter_home': first_quarter_home,
        'second_quarter_home': second_quarter_home,
        'third_quarter_home': third_quarter_home,
        'fourth_quarter_home': fourth_quarter_home,
        'first_quarter_away': first_quarter_away,
        'second_quarter_away': second_quarter_away,
        'third_quarter_away': third_quarter_away,
        'fourth_quarter_away': fourth_quarter_away,
        'event_time': event_time,
    }
    
    gamesbase.append(event_item)

df = pd.DataFrame(gamesbase)

In [235]:
df

,home_team,away_team,first_quarter_home,second_quarter_home,third_quarter_home,fourth_quarter_home,first_quarter_away,second_quarter_away,third_quarter_away,fourth_quarter_away,event_time
0,Chicago Bulls,Detroit Pistons,26,23,18,36,25,21,18,17,09.04. 18:00
1,Indiana Pacers,Detroit Pistons,27,30,30,28,35,38,23,26,08.04. 00:00
2,Detroit Pistons,Brooklyn Nets,34,23,33,18,47,27,22,27,06.04. 00:00
3,Detroit Pistons,Miami Heat,27,25,27,26,31,28,21,38,05.04. 00:00
4,Orlando Magic,Detroit Pistons,34,29,28,37,29,15,24,34,02.04. 23:00
...,...,...,...,...,...,...,...,...,...,...,...
275,Brooklyn Nets,Detroit Pistons,32,38,29,26,30,38,25,22,30.01.2020
276,Detroit Pistons,Cleveland Cavaliers,23,22,27,28,24,29,36,26,28.01.2020
277,Detroit Pistons,Brooklyn Nets,25,35,17,29,26,24,30,26,26.01.2020\nAOT
278,Detroit Pistons,Memphis Grizzlies,23,38,24,27,35,31,26,33,25.01.2020
279,Detroit Pistons,Sacramento Kings,26,31,36,34,27,23,25,31,23.01.2020

In [236]:
df.to_csv('zveda.csv')